name: on-demand-auto-kural
run-name: on-demand-auto-kural 

on: [push]
jobs:
  check-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install kural -g
      - run: sudo npx playwright install-deps  
      
      - name: Screenshots using kural
        run: |
           kural browser:pw:screenshot -s https://login.salesforce.com --help
      
      - name: Commit files
        run: |
          git add screen*.png
          git commit -m "updated screenshot files"
          git push origin HEAD
