name: on-demand-auto-kural
run-name: on-demand-auto-kural 

on: [push]
jobs:
  check-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install kural -g
      
      - name: Screenshots using kural
        run: |
           kural browser:pw:screenshot -s https://login.salesforce.com --help 
  
